### ISSUE TITLE
An IndexError will be reported when epoch = 10 during training 

### ISSUE THREAD

**Issue by huyt16** [Dan123dan/rGBN-RNN#2]
**I tried to use example.txt as the training corpis. An IndexError will be reported when training epoch = 10 as follows.**

Epoch = 10
Traceback (most recent call last):
  File "train_rGBN.py", line 224, in <module>
    Phi, Pi, NDot_Phi, NDot_Pi = update_Pi_Phi(d_train_batch, Phi, Pi, Theta, doc_num_batches, MBObserved, NDot_Phi, NDot_Pi)
  File "train_rGBN.py", line 95, in update_Pi_Phi
    NDot_Phi[l] = (1 - ForgetRate[MBObserved]) * NDot_Phi[l] + ForgetRate[MBObserved] * EWSZS_Phi[l].sum(
IndexError: index 76 is out of bounds for axis 0 with size 70

**Similar IndexError will be reported during training  when using bnc as training corpus as follows.**

Epoch = 10
Traceback (most recent call last):
  File "train_rGBN.py", line 224, in <module>
    Phi, Pi, NDot_Phi, NDot_Pi = update_Pi_Phi(d_train_batch, Phi, Pi, Theta, doc_num_batches, MBObserved, NDot_Phi, NDot_Pi)
  File "train_rGBN.py", line 95, in update_Pi_Phi
    NDot_Phi[l] = (1 - ForgetRate[MBObserved]) * NDot_Phi[l] + ForgetRate[MBObserved] * EWSZS_Phi[l].sum(
IndexError: index 176560 is out of bounds for axis 0 with size 168110

**Comment by Dan123dan** [comment]
Hi! Maybe you should check out the  settings in" config.py", and try to replace Setting['Iterall'] = epoch_size * 110000/Batch_Size with  Setting['Iterall'] = epoch_size * Number of training data/Batch_Size .

**Comment by huyt16** [comment]
> Hi! Maybe you should check out the settings in" config.py", and try to replace Setting['Iterall'] = epoch_size * 110000/Batch_Size with Setting['Iterall'] = epoch_size * Number of training data/Batch_Size .

Thanks for your reply but it doesn't work. I think the value of  Setting['Iterall'] is updated in "train_rGBN.py" as the folloing code.
doc_num_batches = int(np.floor(float(len(train_Doc)) / cf.Batch_Size))
cf.Setting['Iterall'] = cf.epoch_size * doc_num_batches

I tried to replace _cf.Setting['Iterall'] = cf.epoch_size * doc_num_batches_ with _cf.Setting['Iterall'] = int(cf.epoch_size * len(train_Doc) / cf.Batch_Size_, but the IndexError is stilled reported as follows.

Traceback (most recent call last):
  File "train_rGBN.py", line 227, in <module>
    Phi, Pi, NDot_Phi, NDot_Pi = update_Pi_Phi(d_train_batch, Phi, Pi, Theta, doc_num_batches, MBObserved, NDot_Phi, NDot_Pi)
  File "train_rGBN.py", line 95, in update_Pi_Phi
    NDot_Phi[l] = (1 - ForgetRate[MBObserved]) * NDot_Phi[l] + ForgetRate[MBObserved] * EWSZS_Phi[l].sum(
IndexError: index 76 is out of bounds for axis 0 with size 72

**Comment by huyt16** [comment]
Maybe the reason lies in the different between **cf.epoch_size** and **cf.tm_epoch_size**. cf.epoch_size is set to 10 and cf.tm_epoch_size is set to 30 . In "train_rGBN.py", the value of MBObserved will be larger than the size of ForgetRate because MBObserved = int(e * doc_num_batches + batch_id) and e is in range(**cf.tm_epoch_size**) while the shape of ForgetRate, cf.Setting['Iterall'] = **cf.epoch_size** * Number of training data/Batch_Size. Could you please illustrate the difference between **cf.epoch_size** and **cf.tm_epoch_size**?
